Use `nlohmann/json` <3.12
Reason: `nlohmann/json` 3.11.3 and 3.12 are picked for
different environments used by conda build, leading
to problems when `mamba` is being linked:

```
FAILED: micromamba/mamba
: && /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_build_env/bin/x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/work=/usr/local/src/conda/mamba-2.1.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix -D_LIBCPP_DISABLE_AVAILABILITY=1 -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -Wl,-rpath-link,/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -L/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -Wl,--dependency-file=micromamba/CMakeFiles/mamba.dir/link.d micromamba/CMakeFiles/mamba.dir/src/activate.cpp.o micromamba/CMakeFiles/mamba.dir/src/clean.cpp.o micromamba/CMakeFiles/mamba.dir/src/common_options.cpp.o micromamba/CMakeFiles/mamba.dir/src/completer.cpp.o micromamba/CMakeFiles/mamba.dir/src/config.cpp.o micromamba/CMakeFiles/mamba.dir/src/constructor.cpp.o micromamba/CMakeFiles/mamba.dir/src/create.cpp.o micromamba/CMakeFiles/mamba.dir/src/env.cpp.o micromamba/CMakeFiles/mamba.dir/src/info.cpp.o micromamba/CMakeFiles/mamba.dir/src/install.cpp.o micromamba/CMakeFiles/mamba.dir/src/list.cpp.o micromamba/CMakeFiles/mamba.dir/src/login.cpp.o micromamba/CMakeFiles/mamba.dir/src/main.cpp.o micromamba/CMakeFiles/mamba.dir/src/package.cpp.o micromamba/CMakeFiles/mamba.dir/src/remove.cpp.o micromamba/CMakeFiles/mamba.dir/src/repoquery.cpp.o micromamba/CMakeFiles/mamba.dir/src/run.cpp.o micromamba/CMakeFiles/mamba.dir/src/shell.cpp.o micromamba/CMakeFiles/mamba.dir/src/umamba.cpp.o micromamba/CMakeFiles/mamba.dir/src/update.cpp.o micromamba/CMakeFiles/mamba.dir/src/version.cpp.o -o micromamba/mamba  /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libmamba.so.3.0.0  /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libreproc++.so.14.2.4  /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libreproc.so.14.2.4  /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libyaml-cpp.so.0.8.0  -lpthread  /home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libfmt.so.11.1.4 && :
/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: micromamba/CMakeFiles/mamba.dir/src/completer.cpp.o: in function `add_ps_completion(CLI::App*, mamba::Configuration&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool&)::{lambda()#3}::operator()() const':
completer.cpp:(.text._ZZ17add_ps_completionPN3CLI3AppERN5mamba13ConfigurationERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EERbENKUlvE1_clEv+0xd9): undefined reference to `mamba::get_all_running_processes_info(std::function<bool (nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)> const&)'
/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: micromamba/CMakeFiles/mamba.dir/src/env.cpp.o: in function `set_env_command(CLI::App*, mamba::Configuration&)::{lambda()#4}::operator()() const':
env.cpp:(.text._ZZ15set_env_commandPN3CLI3AppERN5mamba13ConfigurationEENKUlvE2_clEv+0x313): undefined reference to `mamba::Console::json_write(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)'
/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: micromamba/CMakeFiles/mamba.dir/src/run.cpp.o: in function `set_ps_command(CLI::App*, mamba::Context&)::{lambda()#3}::operator()() const [clone .isra.0]':
run.cpp:(.text._ZZ14set_ps_commandPN3CLI3AppERN5mamba7ContextEENKUlvE1_clEv.isra.0+0x165): undefined reference to `mamba::get_all_running_processes_info(std::function<bool (nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)> const&)'
/home/conda/feedstock_root/build_artifacts/mamba-split_1745825937885/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: micromamba/CMakeFiles/mamba.dir/src/run.cpp.o: in function `set_ps_command(CLI::App*, mamba::Context&)::{lambda()#1}::operator()() const':
run.cpp:(.text._ZZ14set_ps_commandPN3CLI3AppERN5mamba7ContextEENKUlvE_clEv+0xc74): undefined reference to `mamba::get_all_running_processes_info(std::function<bool (nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)> const&)'
collect2: error: ld returned 1 exit status
```

This is a work-around for now. The same (last) version of
`nlohmann/json` must be used normally (we need to understand
why this is not the case).

Signed-off-by: Julien Jerphanion <git@jjerphan.xyz>